### ISSUE TITLE
Update number of Reports rendered

### ISSUE THREAD

**Issue by stfinnis** [AtlanticR/reproducible-rap-report#6]
@gomezcatalina , in Jake's review (Jakes_review branch), he mentioned it would be good to identify the number of Reports we have provided. We think it is ~15 but wanted to double check with you.

Could you please confirm this is correct? It would be good to include this in the following sections:

- The Abstract
- The Introduction: in the last paragraph, where we mention "In 2018, requests to the division to identify..." Here, it would also be good to identify the # of reports created before the tool was developed.
- Workflow: in Section 2.1: "this work was motivated by repeat requests for data..."
- Discussion: first paragraph

Thank you!!

**Comment by gomezcatalina** [comment]
Thank you! I updated to approximately 20. I liked what you include din the discussion and reiterated the message in the abstract, and checked the other sections.
